# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='nameless', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fore', to='courses.Course')),
                ('whither', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aft', to='courses.Course')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=set([('whence', 'whither')]),
        ),
    ]
