# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default='4ea28435-796c-4bf7-ac73-62b12b264483', on_delete=django.db.models.deletion.DO_NOTHING, to='departments.Department'),
        ),
    ]
