# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160316_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default='11111111-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.SET_DEFAULT, to='departments.Department'),
        ),
    ]
