# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20160324_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tier',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)]),
        ),
    ]
